import { model } from "@medusajs/framework/utils"

/**
 * One row per AI product-creation job. Persisting every stage (research,
 * generated copy, price suggestion, sources) gives the admin an auditable
 * trail and lets the UI poll progress while the workflow runs in background.
 */
const AiProductRequest = model.define("ai_product_request", {
  id: model.id({ prefix: "aipr" }).primaryKey(),
  // Raw product name typed by the admin (e.g. "GAN 356 M").
  input_name: model.text(),
  status: model
    .enum([
      "pending",
      "researching",
      "generating",
      "translating",
      "pricing",
      "creating_product",
      "completed",
      "failed",
    ])
    .default("pending"),
  // Structured research result + the raw web sources it was derived from.
  research_data: model.json().nullable(),
  // Spanish (base language) ecommerce copy generated by the LLM.
  generated_content: model.json().nullable(),
  // English translation of the generated copy.
  translated_content: model.json().nullable(),
  // Market price reference: { min_price, avg_price, max_price, currency,
  // confidence, sources } or { unavailable_reason } when < 2 valid sources.
  price_suggestion: model.json().nullable(),
  // Draft product created at the end of the workflow.
  product_id: model.text().nullable(),
  error: model.text().nullable(),
})

export default AiProductRequest
