// Clickazo storefront — fake catalog. Product imagery uses tasteful
// category panels (a Lucide glyph on a tinted seamless backdrop) as
// placeholders; swap for real warm-graded photography in production.
window.CZ_PRODUCTS = [
  { id:"cz-114", name:"Compiles under pressure tee", cat:"Apparel", icon:"shirt",
    price:28, sale:19.6, rating:4.8, reviews:214, tint:"lime", badge:"sale",
    blurb:"Heavyweight 100% cotton, soft-hand print that won't crack. The line your code wishes it lived up to.",
    tags:["Pre-shrunk","Unisex","240 gsm"] },
  { id:"cz-220", name:"Speed cube — magnetic 3×3", cat:"Cubes", icon:"box",
    price:24, rating:4.9, reviews:512, tint:"violet", badge:"new",
    blurb:"Factory-lubed, magnet-positioned, sub-10-second ready. Corner-cuts like a dream.",
    tags:["Magnetic","48mm","Stickerless"] },
  { id:"cz-309", name:"It works on my machine mug", cat:"Drinkware", icon:"coffee",
    price:18, rating:4.7, reviews:331, tint:"amber",
    blurb:"12oz ceramic, dishwasher-safe, holds enough coffee to ship a feature.",
    tags:["Ceramic","350ml","Microwave-safe"] },
  { id:"cz-401", name:"Mechanical keyboard — 75%", cat:"Desk", icon:"keyboard",
    price:149, sale:129, rating:4.9, reviews:88, tint:"slate", badge:"sale",
    blurb:"Hot-swap switches, gasket mount, knob included. Sounds like a thock, types like butter.",
    tags:["Hot-swap","Wireless","RGB"] },
  { id:"cz-512", name:"Git blame hoodie", cat:"Apparel", icon:"shirt",
    price:62, rating:4.6, reviews:140, tint:"slate",
    blurb:"Midweight fleece, brushed inside, kangaroo pocket deep enough for snacks.",
    tags:["400 gsm","Unisex","Brushed"] },
  { id:"cz-618", name:"Aluminium laptop stand", cat:"Desk", icon:"laptop-minimal",
    price:54, rating:4.8, reviews:97, tint:"slate", badge:"new",
    blurb:"CNC aluminium, folds flat, raises your screen to where your neck wants it.",
    tags:["Aluminium","Foldable","Up to 16\""] },
  { id:"cz-725", name:"Rubber duck — debug edition", cat:"Desk", icon:"bird",
    price:12, rating:5.0, reviews:1204, tint:"amber", badge:"bestseller",
    blurb:"The senior engineer who never judges. Explain your bug out loud, watch it dissolve.",
    tags:["Classic","Squeaks","Float-tested"] },
  { id:"cz-833", name:"Dark mode gym shaker", cat:"Gym", icon:"dumbbell",
    price:22, rating:4.5, reviews:64, tint:"violet",
    blurb:"700ml, leak-proof, matte black. For lifting heavier than your node_modules folder.",
    tags:["700ml","Leak-proof","BPA-free"] },
  { id:"cz-940", name:"USB-C everything cable", cat:"Gadgets", icon:"cable",
    price:16, rating:4.7, reviews:402, tint:"slate",
    blurb:"100W, braided, 2m, reversible both ends. The one cable that finally fits.",
    tags:["100W","2m","Braided"] },
  { id:"cz-1002", name:"Pixel-art desk mat", cat:"Desk", icon:"square-mouse-pointer",
    price:29, rating:4.8, reviews:176, tint:"lime", badge:"new",
    blurb:"900×400 stitched-edge mat. Smooth glide, grippy base, eight-bit energy.",
    tags:["900×400","Stitched","Non-slip"] },
  { id:"cz-1115", name:"Terminal green beanie", cat:"Apparel", icon:"shirt",
    price:24, rating:4.6, reviews:58, tint:"lime",
    blurb:"Ribbed knit, double-folded cuff. Phosphor green, like the good old CRTs.",
    tags:["Acrylic","One size","Ribbed"] },
  { id:"cz-1220", name:"Cube timer — pro mat", cat:"Cubes", icon:"timer",
    price:39, rating:4.9, reviews:73, tint:"violet",
    blurb:"Competition-grade touch timer, 0.001s precision, stack-mat compatible.",
    tags:["0.001s","USB-C","Tournament"] },
];

window.CZ_CATEGORIES = ["All","Apparel","Cubes","Drinkware","Desk","Gym","Gadgets"];
