/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CountryCodeRouteRouteImport } from './routes/$countryCode/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeStorefrontRouteImport } from './routes/$countryCode/_storefront'
import { Route as CountryCodeStorefrontIndexRouteImport } from './routes/$countryCode/_storefront/index'
import { Route as CountryCodeStorefrontStoreRouteImport } from './routes/$countryCode/_storefront/store'
import { Route as CountryCodeStorefrontCheckoutRouteImport } from './routes/$countryCode/_storefront/checkout'
import { Route as CountryCodeStorefrontCartRouteImport } from './routes/$countryCode/_storefront/cart'
import { Route as CountryCodeStorefrontAccountRouteRouteImport } from './routes/$countryCode/_storefront/account/route'
import { Route as CountryCodeStorefrontAccountIndexRouteImport } from './routes/$countryCode/_storefront/account/index'
import { Route as CountryCodeStorefrontProductsHandleRouteImport } from './routes/$countryCode/_storefront/products/$handle'
import { Route as CountryCodeStorefrontCollectionsHandleRouteImport } from './routes/$countryCode/_storefront/collections/$handle'
import { Route as CountryCodeStorefrontCategoriesSplatRouteImport } from './routes/$countryCode/_storefront/categories/$'
import { Route as CountryCodeStorefrontAccountProfileRouteImport } from './routes/$countryCode/_storefront/account/profile'
import { Route as CountryCodeStorefrontAccountAddressesRouteImport } from './routes/$countryCode/_storefront/account/addresses'
import { Route as CountryCodeStorefrontAccountOrdersIndexRouteImport } from './routes/$countryCode/_storefront/account/orders/index'
import { Route as CountryCodeStorefrontOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/_storefront/order/$orderId/confirmed'
import { Route as CountryCodeStorefrontAccountOrdersOrderIdRouteImport } from './routes/$countryCode/_storefront/account/orders/$orderId'
import { Route as CountryCodeStorefrontOrderOrderIdTransferTokenRouteImport } from './routes/$countryCode/_storefront/order/$orderId/transfer/$token'

const CountryCodeRouteRoute = CountryCodeRouteRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeStorefrontRoute = CountryCodeStorefrontRouteImport.update({
  id: '/_storefront',
  getParentRoute: () => CountryCodeRouteRoute,
} as any)
const CountryCodeStorefrontIndexRoute =
  CountryCodeStorefrontIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CountryCodeStorefrontRoute,
  } as any)
const CountryCodeStorefrontStoreRoute =
  CountryCodeStorefrontStoreRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => CountryCodeStorefrontRoute,
  } as any)
const CountryCodeStorefrontCheckoutRoute =
  CountryCodeStorefrontCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => CountryCodeStorefrontRoute,
  } as any)
const CountryCodeStorefrontCartRoute =
  CountryCodeStorefrontCartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => CountryCodeStorefrontRoute,
  } as any)
const CountryCodeStorefrontAccountRouteRoute =
  CountryCodeStorefrontAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => CountryCodeStorefrontRoute,
  } as any)
const CountryCodeStorefrontAccountIndexRoute =
  CountryCodeStorefrontAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CountryCodeStorefrontAccountRouteRoute,
  } as any)
const CountryCodeStorefrontProductsHandleRoute =
  CountryCodeStorefrontProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeStorefrontRoute,
  } as any)
const CountryCodeStorefrontCollectionsHandleRoute =
  CountryCodeStorefrontCollectionsHandleRouteImport.update({
    id: '/collections/$handle',
    path: '/collections/$handle',
    getParentRoute: () => CountryCodeStorefrontRoute,
  } as any)
const CountryCodeStorefrontCategoriesSplatRoute =
  CountryCodeStorefrontCategoriesSplatRouteImport.update({
    id: '/categories/$',
    path: '/categories/$',
    getParentRoute: () => CountryCodeStorefrontRoute,
  } as any)
const CountryCodeStorefrontAccountProfileRoute =
  CountryCodeStorefrontAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => CountryCodeStorefrontAccountRouteRoute,
  } as any)
const CountryCodeStorefrontAccountAddressesRoute =
  CountryCodeStorefrontAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => CountryCodeStorefrontAccountRouteRoute,
  } as any)
const CountryCodeStorefrontAccountOrdersIndexRoute =
  CountryCodeStorefrontAccountOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => CountryCodeStorefrontAccountRouteRoute,
  } as any)
const CountryCodeStorefrontOrderOrderIdConfirmedRoute =
  CountryCodeStorefrontOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => CountryCodeStorefrontRoute,
  } as any)
const CountryCodeStorefrontAccountOrdersOrderIdRoute =
  CountryCodeStorefrontAccountOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => CountryCodeStorefrontAccountRouteRoute,
  } as any)
const CountryCodeStorefrontOrderOrderIdTransferTokenRoute =
  CountryCodeStorefrontOrderOrderIdTransferTokenRouteImport.update({
    id: '/order/$orderId/transfer/$token',
    path: '/order/$orderId/transfer/$token',
    getParentRoute: () => CountryCodeStorefrontRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$countryCode': typeof CountryCodeRouteRouteWithChildren
  '/$countryCode/account': typeof CountryCodeStorefrontAccountRouteRouteWithChildren
  '/$countryCode/cart': typeof CountryCodeStorefrontCartRoute
  '/$countryCode/checkout': typeof CountryCodeStorefrontCheckoutRoute
  '/$countryCode/store': typeof CountryCodeStorefrontStoreRoute
  '/$countryCode/': typeof CountryCodeStorefrontIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeStorefrontAccountAddressesRoute
  '/$countryCode/account/profile': typeof CountryCodeStorefrontAccountProfileRoute
  '/$countryCode/categories/$': typeof CountryCodeStorefrontCategoriesSplatRoute
  '/$countryCode/collections/$handle': typeof CountryCodeStorefrontCollectionsHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeStorefrontProductsHandleRoute
  '/$countryCode/account/': typeof CountryCodeStorefrontAccountIndexRoute
  '/$countryCode/account/orders/$orderId': typeof CountryCodeStorefrontAccountOrdersOrderIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeStorefrontOrderOrderIdConfirmedRoute
  '/$countryCode/account/orders/': typeof CountryCodeStorefrontAccountOrdersIndexRoute
  '/$countryCode/order/$orderId/transfer/$token': typeof CountryCodeStorefrontOrderOrderIdTransferTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$countryCode': typeof CountryCodeStorefrontIndexRoute
  '/$countryCode/cart': typeof CountryCodeStorefrontCartRoute
  '/$countryCode/checkout': typeof CountryCodeStorefrontCheckoutRoute
  '/$countryCode/store': typeof CountryCodeStorefrontStoreRoute
  '/$countryCode/account/addresses': typeof CountryCodeStorefrontAccountAddressesRoute
  '/$countryCode/account/profile': typeof CountryCodeStorefrontAccountProfileRoute
  '/$countryCode/categories/$': typeof CountryCodeStorefrontCategoriesSplatRoute
  '/$countryCode/collections/$handle': typeof CountryCodeStorefrontCollectionsHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeStorefrontProductsHandleRoute
  '/$countryCode/account': typeof CountryCodeStorefrontAccountIndexRoute
  '/$countryCode/account/orders/$orderId': typeof CountryCodeStorefrontAccountOrdersOrderIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeStorefrontOrderOrderIdConfirmedRoute
  '/$countryCode/account/orders': typeof CountryCodeStorefrontAccountOrdersIndexRoute
  '/$countryCode/order/$orderId/transfer/$token': typeof CountryCodeStorefrontOrderOrderIdTransferTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$countryCode': typeof CountryCodeRouteRouteWithChildren
  '/$countryCode/_storefront': typeof CountryCodeStorefrontRouteWithChildren
  '/$countryCode/_storefront/account': typeof CountryCodeStorefrontAccountRouteRouteWithChildren
  '/$countryCode/_storefront/cart': typeof CountryCodeStorefrontCartRoute
  '/$countryCode/_storefront/checkout': typeof CountryCodeStorefrontCheckoutRoute
  '/$countryCode/_storefront/store': typeof CountryCodeStorefrontStoreRoute
  '/$countryCode/_storefront/': typeof CountryCodeStorefrontIndexRoute
  '/$countryCode/_storefront/account/addresses': typeof CountryCodeStorefrontAccountAddressesRoute
  '/$countryCode/_storefront/account/profile': typeof CountryCodeStorefrontAccountProfileRoute
  '/$countryCode/_storefront/categories/$': typeof CountryCodeStorefrontCategoriesSplatRoute
  '/$countryCode/_storefront/collections/$handle': typeof CountryCodeStorefrontCollectionsHandleRoute
  '/$countryCode/_storefront/products/$handle': typeof CountryCodeStorefrontProductsHandleRoute
  '/$countryCode/_storefront/account/': typeof CountryCodeStorefrontAccountIndexRoute
  '/$countryCode/_storefront/account/orders/$orderId': typeof CountryCodeStorefrontAccountOrdersOrderIdRoute
  '/$countryCode/_storefront/order/$orderId/confirmed': typeof CountryCodeStorefrontOrderOrderIdConfirmedRoute
  '/$countryCode/_storefront/account/orders/': typeof CountryCodeStorefrontAccountOrdersIndexRoute
  '/$countryCode/_storefront/order/$orderId/transfer/$token': typeof CountryCodeStorefrontOrderOrderIdTransferTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$countryCode'
    | '/$countryCode/account'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/store'
    | '/$countryCode/'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/profile'
    | '/$countryCode/categories/$'
    | '/$countryCode/collections/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/account/'
    | '/$countryCode/account/orders/$orderId'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/account/orders/'
    | '/$countryCode/order/$orderId/transfer/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$countryCode'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/store'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/profile'
    | '/$countryCode/categories/$'
    | '/$countryCode/collections/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/account'
    | '/$countryCode/account/orders/$orderId'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/account/orders'
    | '/$countryCode/order/$orderId/transfer/$token'
  id:
    | '__root__'
    | '/'
    | '/$countryCode'
    | '/$countryCode/_storefront'
    | '/$countryCode/_storefront/account'
    | '/$countryCode/_storefront/cart'
    | '/$countryCode/_storefront/checkout'
    | '/$countryCode/_storefront/store'
    | '/$countryCode/_storefront/'
    | '/$countryCode/_storefront/account/addresses'
    | '/$countryCode/_storefront/account/profile'
    | '/$countryCode/_storefront/categories/$'
    | '/$countryCode/_storefront/collections/$handle'
    | '/$countryCode/_storefront/products/$handle'
    | '/$countryCode/_storefront/account/'
    | '/$countryCode/_storefront/account/orders/$orderId'
    | '/$countryCode/_storefront/order/$orderId/confirmed'
    | '/$countryCode/_storefront/account/orders/'
    | '/$countryCode/_storefront/order/$orderId/transfer/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryCodeRouteRoute: typeof CountryCodeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/_storefront': {
      id: '/$countryCode/_storefront'
      path: ''
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeStorefrontRouteImport
      parentRoute: typeof CountryCodeRouteRoute
    }
    '/$countryCode/_storefront/': {
      id: '/$countryCode/_storefront/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeStorefrontIndexRouteImport
      parentRoute: typeof CountryCodeStorefrontRoute
    }
    '/$countryCode/_storefront/store': {
      id: '/$countryCode/_storefront/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStorefrontStoreRouteImport
      parentRoute: typeof CountryCodeStorefrontRoute
    }
    '/$countryCode/_storefront/checkout': {
      id: '/$countryCode/_storefront/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeStorefrontCheckoutRouteImport
      parentRoute: typeof CountryCodeStorefrontRoute
    }
    '/$countryCode/_storefront/cart': {
      id: '/$countryCode/_storefront/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeStorefrontCartRouteImport
      parentRoute: typeof CountryCodeStorefrontRoute
    }
    '/$countryCode/_storefront/account': {
      id: '/$countryCode/_storefront/account'
      path: '/account'
      fullPath: '/$countryCode/account'
      preLoaderRoute: typeof CountryCodeStorefrontAccountRouteRouteImport
      parentRoute: typeof CountryCodeStorefrontRoute
    }
    '/$countryCode/_storefront/account/': {
      id: '/$countryCode/_storefront/account/'
      path: '/'
      fullPath: '/$countryCode/account/'
      preLoaderRoute: typeof CountryCodeStorefrontAccountIndexRouteImport
      parentRoute: typeof CountryCodeStorefrontAccountRouteRoute
    }
    '/$countryCode/_storefront/products/$handle': {
      id: '/$countryCode/_storefront/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeStorefrontProductsHandleRouteImport
      parentRoute: typeof CountryCodeStorefrontRoute
    }
    '/$countryCode/_storefront/collections/$handle': {
      id: '/$countryCode/_storefront/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/$countryCode/collections/$handle'
      preLoaderRoute: typeof CountryCodeStorefrontCollectionsHandleRouteImport
      parentRoute: typeof CountryCodeStorefrontRoute
    }
    '/$countryCode/_storefront/categories/$': {
      id: '/$countryCode/_storefront/categories/$'
      path: '/categories/$'
      fullPath: '/$countryCode/categories/$'
      preLoaderRoute: typeof CountryCodeStorefrontCategoriesSplatRouteImport
      parentRoute: typeof CountryCodeStorefrontRoute
    }
    '/$countryCode/_storefront/account/profile': {
      id: '/$countryCode/_storefront/account/profile'
      path: '/profile'
      fullPath: '/$countryCode/account/profile'
      preLoaderRoute: typeof CountryCodeStorefrontAccountProfileRouteImport
      parentRoute: typeof CountryCodeStorefrontAccountRouteRoute
    }
    '/$countryCode/_storefront/account/addresses': {
      id: '/$countryCode/_storefront/account/addresses'
      path: '/addresses'
      fullPath: '/$countryCode/account/addresses'
      preLoaderRoute: typeof CountryCodeStorefrontAccountAddressesRouteImport
      parentRoute: typeof CountryCodeStorefrontAccountRouteRoute
    }
    '/$countryCode/_storefront/account/orders/': {
      id: '/$countryCode/_storefront/account/orders/'
      path: '/orders'
      fullPath: '/$countryCode/account/orders/'
      preLoaderRoute: typeof CountryCodeStorefrontAccountOrdersIndexRouteImport
      parentRoute: typeof CountryCodeStorefrontAccountRouteRoute
    }
    '/$countryCode/_storefront/order/$orderId/confirmed': {
      id: '/$countryCode/_storefront/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodeStorefrontOrderOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeStorefrontRoute
    }
    '/$countryCode/_storefront/account/orders/$orderId': {
      id: '/$countryCode/_storefront/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$countryCode/account/orders/$orderId'
      preLoaderRoute: typeof CountryCodeStorefrontAccountOrdersOrderIdRouteImport
      parentRoute: typeof CountryCodeStorefrontAccountRouteRoute
    }
    '/$countryCode/_storefront/order/$orderId/transfer/$token': {
      id: '/$countryCode/_storefront/order/$orderId/transfer/$token'
      path: '/order/$orderId/transfer/$token'
      fullPath: '/$countryCode/order/$orderId/transfer/$token'
      preLoaderRoute: typeof CountryCodeStorefrontOrderOrderIdTransferTokenRouteImport
      parentRoute: typeof CountryCodeStorefrontRoute
    }
  }
}

interface CountryCodeStorefrontAccountRouteRouteChildren {
  CountryCodeStorefrontAccountAddressesRoute: typeof CountryCodeStorefrontAccountAddressesRoute
  CountryCodeStorefrontAccountProfileRoute: typeof CountryCodeStorefrontAccountProfileRoute
  CountryCodeStorefrontAccountIndexRoute: typeof CountryCodeStorefrontAccountIndexRoute
  CountryCodeStorefrontAccountOrdersOrderIdRoute: typeof CountryCodeStorefrontAccountOrdersOrderIdRoute
  CountryCodeStorefrontAccountOrdersIndexRoute: typeof CountryCodeStorefrontAccountOrdersIndexRoute
}

const CountryCodeStorefrontAccountRouteRouteChildren: CountryCodeStorefrontAccountRouteRouteChildren =
  {
    CountryCodeStorefrontAccountAddressesRoute:
      CountryCodeStorefrontAccountAddressesRoute,
    CountryCodeStorefrontAccountProfileRoute:
      CountryCodeStorefrontAccountProfileRoute,
    CountryCodeStorefrontAccountIndexRoute:
      CountryCodeStorefrontAccountIndexRoute,
    CountryCodeStorefrontAccountOrdersOrderIdRoute:
      CountryCodeStorefrontAccountOrdersOrderIdRoute,
    CountryCodeStorefrontAccountOrdersIndexRoute:
      CountryCodeStorefrontAccountOrdersIndexRoute,
  }

const CountryCodeStorefrontAccountRouteRouteWithChildren =
  CountryCodeStorefrontAccountRouteRoute._addFileChildren(
    CountryCodeStorefrontAccountRouteRouteChildren,
  )

interface CountryCodeStorefrontRouteChildren {
  CountryCodeStorefrontAccountRouteRoute: typeof CountryCodeStorefrontAccountRouteRouteWithChildren
  CountryCodeStorefrontCartRoute: typeof CountryCodeStorefrontCartRoute
  CountryCodeStorefrontCheckoutRoute: typeof CountryCodeStorefrontCheckoutRoute
  CountryCodeStorefrontStoreRoute: typeof CountryCodeStorefrontStoreRoute
  CountryCodeStorefrontIndexRoute: typeof CountryCodeStorefrontIndexRoute
  CountryCodeStorefrontCategoriesSplatRoute: typeof CountryCodeStorefrontCategoriesSplatRoute
  CountryCodeStorefrontCollectionsHandleRoute: typeof CountryCodeStorefrontCollectionsHandleRoute
  CountryCodeStorefrontProductsHandleRoute: typeof CountryCodeStorefrontProductsHandleRoute
  CountryCodeStorefrontOrderOrderIdConfirmedRoute: typeof CountryCodeStorefrontOrderOrderIdConfirmedRoute
  CountryCodeStorefrontOrderOrderIdTransferTokenRoute: typeof CountryCodeStorefrontOrderOrderIdTransferTokenRoute
}

const CountryCodeStorefrontRouteChildren: CountryCodeStorefrontRouteChildren = {
  CountryCodeStorefrontAccountRouteRoute:
    CountryCodeStorefrontAccountRouteRouteWithChildren,
  CountryCodeStorefrontCartRoute: CountryCodeStorefrontCartRoute,
  CountryCodeStorefrontCheckoutRoute: CountryCodeStorefrontCheckoutRoute,
  CountryCodeStorefrontStoreRoute: CountryCodeStorefrontStoreRoute,
  CountryCodeStorefrontIndexRoute: CountryCodeStorefrontIndexRoute,
  CountryCodeStorefrontCategoriesSplatRoute:
    CountryCodeStorefrontCategoriesSplatRoute,
  CountryCodeStorefrontCollectionsHandleRoute:
    CountryCodeStorefrontCollectionsHandleRoute,
  CountryCodeStorefrontProductsHandleRoute:
    CountryCodeStorefrontProductsHandleRoute,
  CountryCodeStorefrontOrderOrderIdConfirmedRoute:
    CountryCodeStorefrontOrderOrderIdConfirmedRoute,
  CountryCodeStorefrontOrderOrderIdTransferTokenRoute:
    CountryCodeStorefrontOrderOrderIdTransferTokenRoute,
}

const CountryCodeStorefrontRouteWithChildren =
  CountryCodeStorefrontRoute._addFileChildren(
    CountryCodeStorefrontRouteChildren,
  )

interface CountryCodeRouteRouteChildren {
  CountryCodeStorefrontRoute: typeof CountryCodeStorefrontRouteWithChildren
}

const CountryCodeRouteRouteChildren: CountryCodeRouteRouteChildren = {
  CountryCodeStorefrontRoute: CountryCodeStorefrontRouteWithChildren,
}

const CountryCodeRouteRouteWithChildren =
  CountryCodeRouteRoute._addFileChildren(CountryCodeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryCodeRouteRoute: CountryCodeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
